import { Action } from "redux";
import { User } from "../model/User";

export enum ACTIONS {
  SIGN_IN_REQUEST = "SIGN_IN_REQUEST",
  SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE = "SIGN_IN_FAILURE",
  SIGN_OUT_REQUEST = "SIGN_OUT_REQUEST",
  SIGNED_OUT = "SIGNED_OUT",
  SEARCH_REQUEST = "SEARCH_REQUEST",
  SEARCH_SUCCESS = "SEARCH_SUCCESS",
  SEARCH_FAILURE = "SEARCH_FAILURE",
  SEARCH_NEXT_REQUEST = "SEARCH_NEXT_REQUEST",
  SEARCH_NEXT_SUCCESS = "SEARCH_NEXT_SUCCESS",
  SEARCH_NEXT_FAILURE = "SEARCH_NEXT_FAILURE",
  LIST_BOOKMARK_REQUEST = "LIST_BOOKMARK_REQUEST",
  LIST_BOOKMARK_SUCCESS = "LIST_BOOKMARK_SUCCESS",
  LIST_BOOKMARK_FAILURE = "LIST_BOOKMARK_FAILURE",
  LIST_BOOKMARK_NEXT_REQUEST = "LIST_BOOKMARK_NEXT_REQUEST",
  LIST_BOOKMARK_NEXT_SUCCESS = "LIST_BOOKMARK_NEXT_SUCCESS",
  LIST_BOOKMARK_NEXT_FAILURE = "LIST_BOOKMARK_NEXT_FAILURE",
  ADD_BOOKMARK_REQUEST = "ADD_BOOKMARK_REQUEST",
  ADD_BOOKMARK_SUCCESS = "ADD_BOOKMARK_SUCCESS",
  ADD_BOOKMARK_FAILURE = "ADD_BOOKMARK_FAILURE",
  REMOVE_BOOKMARK_REQUEST = "REMOVE_BOOKMARK_SUCCESS",
  REMOVE_BOOKMARK_SUCCESS = "REMOVE_BOOKMARK_SUCCESS",
  REMOVE_BOOKMARK_FAILURE = "REMOVE_BOOKMARK_FAILURE",
  ADD_NOTE_REQUEST = "ADD_NOTE_REQUEST",
  ADD_NOTE_SUCCESS = "ADD_NOTE_SUCCESS",
  ADD_NOTE_FAILURE = "ADD_NOTE_FAILURE",
  EDIT_NOTE_REQUEST = "EDIT_NOTE_REQUEST",
  EDIT_NOTE_SUCCESS = "EDIT_NOTE_SUCCESS",
  EDIT_NOTE_FAILURE = "EDIT_NOTE_FAILURE",
}

interface SignInRequestAction extends Action {
  type: ACTIONS.SIGN_IN_REQUEST,
}
interface SignInSuccessAction extends Action {
  type: ACTIONS.SIGN_IN_SUCCESS,
  payload: User,
}
interface SignOutRequestAction extends Action {
  type: ACTIONS.SIGN_OUT_REQUEST,
  payload: User,
}
interface SignedOutAction extends Action {
  type: ACTIONS.SIGNED_OUT,
  payload: User,
}

export type UserActionTypes = SignInRequestAction | SignInSuccessAction | SignOutRequestAction | SignedOutAction;
